### ISSUE TITLE
Correction in README.md file.

### ISSUE THREAD

**Issue by BenjaminSemah** [BertrandConxy/online-bookstore#3]
Hello @BertrandConxy 

Great job done so far on this project. 👍 While going through the Readme file, I observed an `issue` that needs to be resolved.

Check the `USAGE` section.
Under the **Run and use this project on your local machine** part.

To change directly after cloning, users should 
cd to `online-bookstore` instead of `LeaderBoard-app`

Best wishes!  😃

**Comment by BertrandConxy** [comment]
Hello @BenjaminSemah 

I am really glad for your review. I haven't noticed that. You know when it comes to README,  I copy it and paste it somewhere.
Thank you very much, I am going to correct that. 😃 
Happy coding.
